name: Lint and Test

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: ""

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get Python version from pyproject.toml
        run: |
          PYTHON_VERSION=$(grep "requires-python" pyproject.toml | sed -E 's/.*>=([0-9]+\.[0-9]+).*/\1/')
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.uv
          key: uv-dependencies-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            uv-dependencies-${{ runner.os }}-

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install ${{ env.PYTHON_VERSION }}

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Run Black
        run: |
          uv run black .
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git diff --exit-code || (git add . && git commit -m "style: auto-format with Black" && git push)

      - name: Run Pyflakes
        run: uv run pyflakes . || true

      - name: Run Tests
        run: uv run pytest --verbose