name: Publish to TestPyPI

on:
  push:
    branches:
      - develop

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint_and_test.yml
    with:
      python-version: "3.10"

  publish:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Cache uv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.uv
          key: uv-dependencies-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            uv-dependencies-${{ runner.os }}-

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python
        run: uv python install

      - name: Sync dependencies
        run: uv sync --all-extras --dev

      - name: Build and Publish to TestPyPI
        run: |
          uv run python -m build
          uv run twine upload --repository testpypi dist/* \
            -u ${{ secrets.TEST_PYPI_USERNAME }} \
            -p ${{ secrets.TEST_PYPI_PASSWORD }}